background {
    monitor =
    # path = screenshot
    color = rgba(30, 30, 46, 1)
    blur_passes = 0.5
    blur_size = 7
}

label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    placeholder_text = <i>what's the secret?</i>
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(89b4faee) rgba(b4befeee) 45deg
    check_color=rgba(fab387ee) rgba(f9e2afee) 120deg
    fail_color=rgba(f38ba8ee) rgba(f5cwe7ee) 40deg

    font_color = rgb(143, 143, 143)
    font_family = JetBrainsMono Nerd
    fade_on_empty = false
    rounding = 6

    position = 0, -20
    halign = center
    valign = center
}
