hl.on("hyprland.start", function () 
  -- hl.exec_cmd(terminal)
  -- hl.exec_cmd("nm-applet")
  hl.exec_cmd("brave", { workspace = "1 silent" })
  hl.exec_cmd(terminal, { workspace = "2 silent" })
  hl.exec_cmd("waybar & hyprpaper")
end)
